# Generated by Django 2.2.5 on 2022-06-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20220624_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='instanct_book',
        ),
        migrations.AddField(
            model_name='room',
            name='instant_book',
            field=models.BooleanField(default=False),
        ),
    ]
