BBBB BBBB
XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXX
  XXXXXXXXXXXX XXXX XXXXX XXXX  gettext(u'This is clone-coding of airbnb') XXXXXXXX
XXXXXXXXX
