BBBB BBBBBB
XXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXX
  BB BBBBBBBBBBBBBBBBBBBBB
    XXX XXXXXXXXXXXXXXXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBXX
        BB BBBBBBBBBBBBBBBBBBBBBBBBBB
          XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        BBBB
          XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        BBBBB
      XXXX
    XXXXX
    BB BBBBBBBBBBBBBBBBBBBBBBBBBB
      XXX XXXXXXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBXXXXXXXX XXXXXXXX
      XXXXX
    BBBBB
    XXX XXXXXXXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXXXXX
    XXXXX
    XXX XXXXXXXXXXXXXXXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBXXXXX XXXXXXX
    XXXXX
  BBBB
    XXX XXXXXXXXXXXXXXXXX
      XX XXXXXXBBB BBBBBBBBBBBBBXXXXX XXXXXX
    XXXXX
    XXX XXXXXXXXXXXXXXXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBXXXXXX XXXXXX
    XXXXX
  BBBBB
XXXXX
