XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXX
   XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBX
      XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXX
   XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBX
      XXXXXXXXXX XXXXXXXX  XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXX
XXXXXX
XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXX
   XXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX
   XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX
   XXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX
XXXXXX
