BB BBBBBBBBBBBBBBB
    XXXX XXXXXXXFFFFFFFFFFFFF FFFFF XXXXXXXXXXXX XXXXXXXXX
         XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
    XXXXXX
BBBB
    XXXX XXXXXXXFFFFFFFFFFFFF FFFFF XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXFFFFFFFFFFFFFFFFFFXXFFFFFXXXXXXX
    XXXXXX
BBBBB
