 #
 #

BBBBBBB BBBBBBBBBBB
BBBBB BBBBBBBBBB
    XXXXXX
BBBBBBBB BBBBBBBBBB
BBBBB BBBBBBBBBB
BBBBBBBB BBBBBBBBBB
BBBBB BBBBBBB
    XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBXX
        XXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XX XXXXX XX
        XXXXXX
        XXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
                BBB BBBBBBB BB BBBBBBBBB
                    XXXXXXX XXXXXXXX
                            BB BBBBBBBBBBBB BB BBBBBBBBBXXXXXXXXBBBBBX
                        
                    XXXXXXXXX
                BBBBBB
            XXXXXXXXX
        XXXXXX
        XXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXX BB BBBBBBBBBBB BB BXXXXXXXXBBBBBX
                    XXX XXXX
                XXXXXXXXX
                BBB BBBBBBBBB BB BBBBBBBBBB
                    XXXXXXX XXXXXXXX
                            BB BBBBBBBBBBB BB BBBBBBBBBBBBXXXXXXXXBBBBBX
                        
                    XXXXXXXXX
                BBBBBB
            XXXXXXXXX
        XXXXXX
        XXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXX
                   XXXXXXXXXXXXX
                   XXXXXXXXXXXX
                   XXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXX
                   XXXXXXXXXXXXX
                   XXXXXXXXXXXXX
                   XXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXX
                   XXXXXXXXXXXXX
                   XXXXXXXXXXXXXXX
                   XXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXX
                   XXXXXXXXXXXXX
                   XXXXXXXXXXX
                   XXXXXXXXX
                   XXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXX
                   XXXXXXXXXXXXX
                   XXXXXXXXXXXX
                   XXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXX
                   XXXXXXXXXXXX
                   BB BBBBBBBXXXXXXXBBBBBXX
        XXXXXX
        XXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXX
                   BB BBBBBBBBBXXXXXXXBBBBBXX
        XXXXXX
        XXXXX
            XXXXXXXXXXXXXXXXXX
            XXXX
                BBB BBBBBBB BB BBBBBBBBB
                    XXXX
                        XXXXXX XXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX BB BBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBXXXXXXXBBBBB XX
                    XXXXX
                BBBBBB
            XXXXX
        XXXXXX
        XXXXX
            XXXXXXXXXXXXXXXXXX
            XXXX
                BBB BBBBBBBB BB BBBBBBBBBB
                    XXXX
                        XXXXXX XXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX BB BBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBXXXXXXXBBBBB XX
                    XXXXX
                BBBBBB
            XXXXX
        XXXXXX
        XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX
    XXXXXXXXXXXXXXXX
    BBB BBBB BB BBBBBXXXXXXXXXBBBBBB
BBBBBBBB BBBBBBB
