BBBBBBB BBBBBBBBBBB
BBBBB BBBBBBBBBB
    XXXXXX XXXX
BBBBBBBB BBBBBBBBBB
BBBBB BBBBBBBBBB
BBBBBBBB BBBBBBBBBB
BBBBB BBBBBBB
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXX XXXXX XXXX XXXXXXXX XXXXXXXXXXXX XXXXXX XXX XXXXXXXXXXXXXXXXX
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBB BBBBBBBBBBB BBBBB
        XXXX XXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBB BBBBBBBX
               XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
        XXXXXX
    XXXXXX
BBBBBBBB BBBBBBB
