BBBBBBB BBBBBBBBBBB
BBBBB BBBBBBBBBB
    XXXX
BBBBBBBB BBBBBBBBBB
BBBBB BBBBBBB
    XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXX XXXXX XXXXX XXXXXXXX XXXXXXXXXX
             XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXX
            BBB BBBB BB BBBBB
                BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBB
            BBBBBB
        XXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXX
            BB BBBBBBBBBBBBBBBBBBBBB
                XX XXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
            BBBBB
            XXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XX XXXXXXX
            BB BBBBBBBBBBBBBBBBB
                XX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
            BBBBB
        XXXXXX
    XXXXXX
BBBBBBBB BBBBBBB
