BBBBBBB BBBBBBBBBBB
BBBBB BBBBBBBBBB
    XX XXXXXX
BBBBBBBB BBBBBBBBBB
BBBBB BBBBBBBBBB
BBBBBBBB BBBBBBBBBB
BBBBB BBBBBBB
    XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXX XXXX XXXXXXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBB BBBBBBBX
               XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXX
        XXXXXX
        BBB BBBBB BB BBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXX XXXXXX XXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXXXXXXXXXXX
                    XXXX XXXXXX XXXXXXXXXXX XXXXX XX
                    XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXX XXXXXXXX XXXXXXX
                    XX XXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBX
                       XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBX
                       XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
            XXXXXX
        BBBBBB
        XXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
            XX XXXXXXBBB BBBBBBBBBBBB BBBBBBBX
               XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XX XXXX XXXXXXXX
        XXXXXX
    XXXXXX
BBBBBBBB BBBBBBB
