BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBBB
BBBBB BBBBBBBBBB
    
BBBBBBBB BBBBBBBBBB
BBBBB BBBBBBB
    XXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXX XXXX XXXXXXX
        XXXX XXXXXXXXXXXXX XXXXX XXXXXXXXX XXXXXXXXX
             XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXX XXXXX XXXX XXXXXXXXXXX
            BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
                     XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
                XXXXXX
            BBBBBB
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXXXX XXXXXXX
        XXXX XXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
                XXXXX
                    XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX
                XX XXXXXXX
                   XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX
                    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBB
                    XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXX
            XXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXFFFFFFFFFXXXXXXX
                XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXFFFFFFFFFXXXXXXX
                XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXFFFFFFFFFXXXXXXX
                XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXFFFFFFFFFXXXXXXX
            XXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX
                BBB B BB BBBBBBBBBBBBBBBBBBXXX XXXXXXXXXXXXXXXXXXBBBBBB
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX
                BBB B BB BBBBBBBBBBBBBBBBBBBXXX XXXXXXXXXXXXXXXXXXBBBBBB
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXX
                BBB B BB BBBBBBBBBBBBBBBBBBBBXXX XXXXXXXXXXXXXXXXXXBBBBBB
            XXXXXX
            XXXX XXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                    XXXXX
                        XX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXX
                    XXXXX
                        XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXFFFFFFFFFXXXXXXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXX
                    BBB BBBBBB BB BBBBBBBBBBBBBBBB
                        XXXX XXXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXX XXXXXX
                                XXXXXBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBB BBBBB BBBBBBBBBBBBBBBBBBBXXXXXX
                                XXXX XXXXXXXXXXX XXXXXXXX XXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXFFFFFFF FFXXXXXXX
                                XXXXXX
                            XXXXXX
                            XXXXXXX
                        XXXXXX
                    BBBBBB
                XXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXX
            BB BBBBBBBBB BB BBBB
                XX XXXXXXBBB BBBBBBBBBBBB BBBBBBBX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX
            BBBB
                BB BBB BBBBBBBBBBBBBBBBBBBBBBBBBB
                    BBB BBBBBBBB BB BBBBBBBBBBBBBBBBBB
                        XXXX XXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXX XXXXXX X XXXXXXX
                            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX
                                BBB BBB BB BBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBBB
                            XXXXXX
                            XXXX XXXXXXXXXXXXXXXXX
                                BBB BBBBBBBB BB BBBBBBBBBBBBBBBBB
                                    BBBBBBBBB BBBB BBBBBBBB BB BBBBBBBBBBBBBB
                                    BB BBBBBBBBBBBBBBB BB B
                                        BB BBBBBBBBBBBBB
                                            XXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXX
                                        BBBB BBBBBBBBBBBBBB
                                            XXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXX XXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                                        BBBB
                                            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBB BBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBBBBBX
                                               XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                                        BBBBB
                                    BBBB
                                        XXXXXXXXXXXXX
                                    BBBBB
                                BBBBBB
                            XXXXXX
                        XXXXXX
                    BBBBBB
                BBBBB
            BBBBB
        XXXXXX
    XXXXXX
BBBBBBBB BBBBBBB
