BBBBBBB BBBBBBBBBBB
BBBBB BBBBBBBBBB
    XXXXXX
BBBBBBBB BBBBBBBBBB
BBBBB BBBBBBBBBB
BBBBBBBB BBBBBBBBBB
BBBBB BBBBBBB
    XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBXX
        
        XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX
    BB BBBBB BB BBBB
        XXXXXXXXXXXXXXXX
        BBB BBBB BB BBBBBXXXXXXXXXBBBBBB
    BBBBB
BBBBBBBB BBBBBBB
