BBBB BBBB
BBBB BBBBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
  XXXXXX
    XXXXX XXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBX XX
    XXXXXXX
      BBBBB BBBBBBBBBB
      BBBBBBBB BBBBBBBBBB
    X XXXXXXXXXXXX
  XXXXXXX
  XXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXX
      XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
        XX XXXXXX BBB BBBBBBBBBBBX XXXXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBX XX
        XXXX
        BBBBB BBBBBBBBBB
          XXXXX XXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXX XXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXX
                   XXXXXXXXXXXXX gettext(u'Search by City') XXX
          XXXXXXX
        BBBBBBBB BBBBBBBBBB
      XXXXXX
      BBBBBBB BBBBBBBBBBBBBBBBBBB
    XXXXXXXXX
    BBBBB BBBBBBB
    BBBBBBBB BBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
  XXXXXXX
XXXXXXX
