BBBBBBB BBBBBBBBBBB
BBBBB BBBBBBBBBB
    XXXXXXXXXXX 
BBBBBBBB BBBBBBBBBB
BBBBB BBBBBBBBBB
BBBBBBBB BBBBBBBBBB
BBBBB BBBBBBB
    XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXX XXXX XXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXXX
             XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXXXXX
                 X 
                XXXXX XXXXXXXXXXX BB BBBBBBBBBBBBBBBBBB BB BBBBBBBBBXXXXXXXXXXXXXXX BBBB BBBBBBBBBBBBBBBBBB BB BBBBBBBBBBXXXXXXXXXXXX BBBBXXXXXXXXXXXXX BBBBBXXXXXXXXX
            XXXXXX
            XXXXX XXXXXXXXXXXXXXX XXXXXXXX XXX XXXX XXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXX XXXXXXXX XXXXXXXX
                XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX
                    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                    XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXX XXXX XXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXX
                    XX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXX
                XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXX XXXXXX
                BB BBBBBBBBBBBBBBBBBB BB BBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBB
                    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXX XXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX
                    XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBX
                          XXXXXXXXXXXXX
                          XXXXXXXXXXXX XXXXXXXXX
                        BBBBBBBBBB
                        
                        XXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXXXXX
                BBBB
                    BB BBBBBBBBBBBBBBBBBB BB BBBBBBBBB
                        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBX
                           XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
                        BB BBBBBBBBBBBBBBBBBBBBB BB BBBB
                            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBX
                               XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                        BBBBB
                    BBBBB
                BBBBB
            XXXXXX
        XXXXXX
    XXXXXX
BBBBBBBB BBBBBBB
