BBBBBBB BBBBBBBBBBB
BBBBB BBBBBBBBBB
    XXX XX
BBBBBBBB BBBBBBBBBB
BBBBB BBBBBBBBBB
BBBBBBBB BBBBBBBBBB
BBBBB BBBBBBB
    XXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXX XXXXX XXXX XXXXXXXX XXXXXXXXXXXX XXXXXX XXX XXXXXXXXXXXXXXXXX
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBB BBBBBBBB BBB
        XXXX XXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXX XXXX XX XXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX
        XXXXXX
    XXXXXX
BBBBBBBB BBBBBBB
