BBBBBBB BBBBBBBBBBB
BBBBB BBBBBBBBBB
    XXXX XX
BBBBBBBB BBBBBBBBBB
BBBBB BBBBBBBBBB
BBBBBBBB BBBBBBBBBB
BBBBB BBBBBBB
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXX XXXXX XXXX XXXXXXXX XXXXXXXXXXXX XXXXXX XXX XXXXXXXXXXXXXXXXX
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBB BBBBBBBBB BBB
        XXXX XXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
        XXXXXX
    XXXXXX
BBBBBBBB BBBBBBB
