BBBBBBB BBBBBBBBBBB
BBBBB BBBBBBBBBB
    XXXXXX XXXXXXXX
BBBBBBBB BBBBBBBBBB
BBBBB BBBBBBBBBB
BBBBBBBB BBBBBBBBBB
BBBBB BBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXX XXXXX XXXX XXXXXXXX XXXXXXXXXXXX XXXXXX XXX XXXXXXXXXXXXXXXXX
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBB BBBBBBBBBBB BBBBBBBBB
        XXXXXX
    XXXXXX
BBBBBBBB BBBBBBB
