BBBBBBB BBBBBBBBBBB
BBBBB BBBBBBBBBB
    XX XXXXXXX
BBBBBBBB BBBBBBBBBB
BBBBB BBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXX XXXXX XXXX XXXXXXXX XXXXXXXXXXXX XXXXXX XXX XXXXXXXXXXXXXXXXX
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBB
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
                BB BBBBBBBBBBBBBBBBBBXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXBBBBB
            XXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXX
            BB BBBB BB BBBBBBBB
                XX XXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
            BBBBB
        XXXXXX
        BB BBBBBBBBBBBBBBBBBBBB B B
            XXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXX
                XXXX XXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXX
                    BBB BBBB BB BBBBBBBBBBBBBBBBBB
                        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBB
                    BBBBBB
                XXXXXX
            XXXXXX
        BBBBB
    XXXXXX
BBBBBBBB BBBBBBB
