BBBBBBB BBBBBBBBBBB
BBBBB BBBBBBBBBB
    XXXXXX XXXXXXX
BBBBBBBB BBBBBBBBBB
BBBBB BBBBBBBBBB
BBBBBBBB BBBBBBBBBB
BBBBB BBBBBBB
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXX XXXXX XXXX XXXXXXXX XXXXXXXXXXXX XXXXXX XXX XXXXXXXXXXXXXXXXX
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBB BBBBBBBBBBB BBBBBBBB
        BB BBBBBBBBBBBBBBBBBBB BB BBBBBBB
            XXXX XXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
            XXXXXX
        BBBBB
    XXXXXX
BBBBBBBB BBBBBBB
